#定期的に送信するメッセージ
Messages:
  - "tips(1番目)"
  - "tips(2番目)"
  - "tips(3番目)"
  - "tips(4番目)"
  - "tips(5番目)"

#何ティックに1回メッセージを送信するか 20 = 1秒
tick: 6000

#設定したメッセージすべてが送信されるまで
#今まで送信したメッセージが送信されないかどうか
# true = すべて送信するまで今までのメッセージは送信しない
AllSendMessage: true